name: Continuous Deployment with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, test-ec2]  # Self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: _work/test-repo # Optional: Specify a target directory

      - name: Navigate to project directory
        run: cd _work/test-repo # Replace with your project's directory

      - name: Install dependencies
        run: npm install

      - name: Restart Application
        run: pm2 restart all || pm2 start server.js
