name: Continuous Deployment with Self-Hosted Runner

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  deploy:
    runs-on: [self-hosted, test-ec2]  # Self-hosted runner
    steps:
      - name: project directory
        run: ls
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: test-server/_work/test-repo
        
      - name: Navigate to project directory
        run: cd test-server/_work/test-repo

      - name: Print full directory path
        run: pwd  # This prints the full directory path
        
      - name: List files in the project directory
        run: ls

      - name: Install dependencies
        run: npm install

      - name: Restart Application
        run: pm2 restart all || pm2 start server.js
